backoffice/urls.py
from django.urls import path
from backoffice import views


urlpatterns = [
    # LOGIN
    path('login', views.loginView, name='login'),
    
    # INDEX
    path('', views.indexView, name='index'),

    # CLIENTS
    path('all-clients', views.allClientsView, name='all-clients'),
    path('client-details/<str:pk>/', views.clientDetailView, name='client-details'),
    path('new-client', views.newClientView, name='new-client'),
    
    # PRODUCTS
    path('all-products', views.allProductsView, name='all-products'),
    path('product-details/<str:pk>/', views.productDetailView, name='product-details'),
    path('new-product', views.newProductView, name='new-product'),

    # ORDERS
    path('all-orders', views.allOrdersView, name='all-orders'),
    path('order-details/<str:pk>/', views.orderDetailView, name='order-details'),
    path('new-order', views.newOrderView, name='new-order'),
    path('generate-order-delivery', views.generateOrderDelivery, name='generate-order-delivery'),
    path('order-delivery', views.orderDelivery, name='order-delivery'),
    path('order-done', views.orderDone, name='order-done'),
    path('change-order-status', views.changeOrderStatus, name='change-order-status'),
    path('order-delete', views.orderDelete, name='order-delete'),

    # SALES
    path('all-sales', views.allSalesView, name='all-sales'),

    # COMPRAS
    path('all-spendings', views.allSpendingsView, name='all-spendings'),
    path('new-spending', views.newSpendingView, name='new-spending'),
    path('new-purchase', views.newPurchaseView, name='new-purchase'),

]

deia/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('', include('backoffice.urls')),
]

urlpatterns += staticfiles_urlpatterns()

backoffice/models.py
from django.db import models

# Create your models here.
# TODO O BANCO DE DADOS VAI FICAR AQUI, foda-se

class Client(models.Model):
    def __str__(self):
        return self.name
    # SELF FIELDS
    name = models.CharField(max_length=255)
    cpf = models.CharField(max_length=31, null=True, blank=True)
    date_of_creation = models.DateField(auto_now_add=True)
    class Meta:
        ordering = ['name']

class Phone(models.Model):
    # FOREIGN KEY
    client = models.OneToOneField(Client, on_delete=models.CASCADE)
    # SELF FIELDS
    number = models.CharField(max_length=31)
    description = models.CharField(max_length=127, null=True, blank=True)

class Address(models.Model):
    # FOREIGN KEY
    client = models.OneToOneField(Client, on_delete=models.CASCADE)
    # SELF FIELDs
    description = models.CharField(max_length=127, null=True, blank=True)
    number = models.CharField(max_length=15, null=True, blank=True)
    street = models.CharField(max_length=255, null=True, blank=True)
    district = models.CharField(max_length=127, null=True, blank=True)
    state = models.CharField(max_length=63, null=True, blank=True)
    postal_code = models.CharField(max_length=31, null=True, blank=True)
    latitude = models.CharField(max_length=31, null=True, blank=True)
    longitude = models.CharField(max_length=31, null=True, blank=True)

class Product(models.Model):
    def __str__(self):
        return self.title
    # SELF FIELDS
    title = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    buy_value = models.FloatField()
    sell_value = models.FloatField()
    stock = models.IntegerField()
    is_active = models.BooleanField(default=True)
    class Meta:
        ordering = ['title']

class Order(models.Model):
    # FOREIGN KEY
    client = models.ForeignKey(Client, on_delete=models.PROTECT)
    # CHOICES
    STATUS = (
        (0, 'Encomendado'),
        (1, 'Separado'),
        (2, 'Saiu para Entrega'),
        (3, 'Entregue'),
    )
   
    # SELF DATA
    date = models.DateField(auto_now=False, null=False)
    status = models.IntegerField(choices = STATUS)


class OrderProductList(models.Model):
    # FOREIGN KEY
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    # SELF FIELDS
    amount = models.IntegerField()
    value = models.FloatField()


class Sale(models.Model):
    # FOREIGN KEY
    client = models.ForeignKey(Client, on_delete=models.PROTECT)
    # SELF FIELDS
    date = models.DateTimeField(auto_now=True)
    total_value = models.FloatField()
    liquid_value = models.FloatField()
    def __str__(self):
        return self.client.name
    class Meta:
        ordering = ['-date']


# PURCHASES

# Compras/Gastos Variáveis
class Spending(models.Model):
    CHOICES = (
        (0, 'Combustível'),
        (1, 'Reparos'),
        (2, 'Outros'),
    )
    description = models.TextField(null=True)
    value = models.FloatField(null=False)
    date = models.DateField(auto_now=False, null=False)
    tipo = models.IntegerField(choices = CHOICES)

    
class Purchase(models.Model):
    date = models.DateTimeField(auto_now=False)
    value = models.FloatField(null=False)

class PurchaseProductList(models.Model):
    # FOREIGN KEY
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    purchase = models.ForeignKey(Purchase, on_delete=models.CASCADE)
    # SELF FIELDS
    amount = models.IntegerField()
    value = models.FloatField()

backoffice/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.db.models import Sum
from django.db.models.functions import TruncMonth, ExtractMonth

from backoffice.models import *
from backoffice.forms import *

from datetime import datetime

# Create your views here.

@login_required(login_url="login")
def indexView(request):
    # ACTUAL MONTH AND YEAR
    currentMonth = datetime.now().month
    currentYear = datetime.now().year
    # GET MONTHLY SALES
    sales = Sale.objects.filter(
            date__year__gte=currentYear,
            date__month__gte=currentMonth,
        ).aggregate(earning = Sum('total_value'))['earning']
    if (sales):
        earning = '{:,.2f}'.format(sales)
    else:
        earning = 'Nenhum'
    
    # Cálculo do Lucro mensal
    liquid_sales = Sale.objects.filter(
            date__year__gte=currentYear,
            date__month__gte=currentMonth,
        ).aggregate(earning = Sum('liquid_value'))['earning']
    if (liquid_sales):
        lucro = '{:,.2f}'.format(liquid_sales)
    else:
        lucro = 'Nenhum'
    # GET MONTHLY SPENDINGS
    spending = Spending.objects.filter(
            date__year__gte=currentYear,
            date__month__gte=currentMonth,
        ).aggregate(earning = Sum('value'))['earning']
    if (spending):
        spending = '{:,.2f}'.format(spending)
    else:
        spending = 'Nenhum'
    
    # Gráfico
    #meses = 
    #metrics = {
    #    'sales_sum': Sum('total_value'),
    #}
    #dados = Sale.objects.annotate(valor = Sum('total_value'), month=ExtractMonth('date')).values('month')
    #print(dados)
    context = {
        'vazio': 'vazio',
        'earning': earning,
        'spending': spending,
        'lucro': lucro,
    #    'dados': dados,
    }
    return render(request, "backoffice/dashboard.html", context)

def loginView(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, "Bem-vindo!")
            return redirect('/')
        else:
            messages.error(request, "Usuário e/ou Senha incorreto(s)")
            return redirect('/')
    else:
        return render(request, "backoffice/login.html")


# ------------------------------------------------------------------- #
# ------------------------------------------------------------------- #
# ---------------------------- CLIENTS ------------------------------ #
# ------------------------------------------------------------------- #
# ------------------------------------------------------------------- #


@login_required(login_url="login")
def newClientView(request):
    if request.method == 'POST':
        client_form = []
        phone_form = []
        address_form = []
        # GET CLIENT DATA FROM FORM
        client_form = {
            'name':request.POST['name'],
            'cpf':request.POST['cpf']
        }
        # GET PHONE DATA FROM FORM
        phone_form = {
            'number':request.POST['phone'],
            'description':request.POST['phone_description']
        }
        # GET ADDRESS DATA FROM FORM
        address_form = {
            'number':request.POST['number'],
            'street': request.POST['street'],
            'district': request.POST['district'],
            'city': request.POST['city'],
            'state': request.POST['state'],
            'postal_code': request.POST['postal_code'],
            'description': request.POST['address_description'],
            'latitude': request.POST['latitude'],
            'longitude': request.POST['longitude']
        }

        # CREATE CLIENT
        client = Client.objects.create(
            name = client_form['name'],
            cpf = client_form['cpf'], 
            )
        client.save()
        # CREATE PHONE
        phone = Phone.objects.create(
            client = client,
            number = phone_form['number'], 
            description = phone_form['description'], 
            )
        phone.save()
        # CREATE ADDRESS
        address = Address.objects.create(
            client = client,
            number = address_form['number'], 
            street = address_form['street'], 
            district = address_form['district'],
            state = address_form['state'], 
            postal_code = address_form['postal_code'], 
            description = address_form['description'],
            latitude = address_form['latitude'], 
            longitude = address_form['longitude'],
            )
        address.save()
        messages.success(request, "Cliente cadastrado!")
        return redirect('/')
        '''else:
            messages.error(request, 'Algum dado inválido!')
            return redirect('/new-client')
            '''
    
    return render(request, "backoffice/new-client.html")



@login_required(login_url="login")
def allClientsView(request):
    clients = Client.objects.all()
    context = {
        'clients':clients,
    }
    return render(request, "backoffice/all-clients.html", context)


@login_required(login_url="login")
def clientDetailView(request, pk):
    # LOAD DATA FROM ESPECIFIC CLIENT
    client = Client.objects.get(id = pk)
    address = Address.objects.get(client = client.id)
    # FORMS
    client_form = ClientDetailForm(instance=client)
    address_form = ClientAddressForm(instance=address)
    if request.method == 'POST':
        form = ClientDetailForm(request.POST, instance=client)
        if form.is_valid():
            form.save()
            messages.success(request, "Client's info updated!")
            return redirect('/client-details/' + pk)
    context = {
        'client_form':client_form,
        'address_form':address_form,
        'client':client,
        }
    return render(request, "backoffice/client-details.html", context)


# ------------------------------------------------------------------- #
# ------------------------------------------------------------------- #
# ---------------------------- PRODUCTS ----------------------------- #
# ------------------------------------------------------------------- #
# ------------------------------------------------------------------- #

@login_required(login_url="login")
def allProductsView(request):
    products = Product.objects.all()
    total_amount = 0
    total_sell_value = 0
    total_buy_value = 0
    for product in products:
        total_amount += product.stock
        total_sell_value += product.stock * product.sell_value
        total_buy_value += product.stock * product.buy_value
    context = {
        'products':products,
        'total_amount':total_amount,
        'total_sell_value':total_sell_value,
        'total_buy_value':total_buy_value,

    }
    return render(request, "backoffice/all-products.html", context)

@login_required(login_url="login")
def productDetailView(request, pk):
    # LOAD DATA FROM ESPECIFIC PRODUCT
    product = Product.objects.get(id = pk)
    # FORMS
    product_form = ProductDetailForm(instance=product)
    if request.method == 'POST':
        form = ProductDetailForm(request.POST, instance=product)
        if form.is_valid():
            form.save()
            messages.success(request, "Produto atualizado!")
            return redirect('/product-details/' + pk)
    context = {
        'product_form':product_form,
    }
    return render(request, "backoffice/product-details.html", context)

@login_required(login_url="login")
def newProductView(request):
    if request.method == 'POST':
        form = NewProductForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Produto Cadastrado!")
            return redirect('/')
    else:
        return render(request, "backoffice/new-product.html")

# ------------------------------------------------------------------- #
# ------------------------------------------------------------------- #
# ----------------------------- ORDERS ------------------------------ #
# ------------------------------------------------------------------- #
# ------------------------------------------------------------------- #

@login_required(login_url="login")
def allOrdersView(request):
    orders = Order.objects.all().order_by('-id')
    context = {
        'orders':orders,
    }
    return render(request, "backoffice/all-orders.html", context)

@login_required(login_url="login")
def orderDetailView(request, pk):
    # LOAD DATA FROM ESPECIFIC ORDER
    order = Order.objects.get(id = pk)
    client = Client.objects.get(id = order.client.id)
    address = Address.objects.get(client = client)
    products = OrderProductList.objects.filter(order = order)
    # FORMS
    order_form = OrderDetailForm(instance=order)
    if request.method == 'POST':
        form = OrderDetailForm(request.POST, instance=order)
        if form.is_valid():
            form.save()
            messages.success(request, "Pedido atualizado!")
            return redirect('/order-details/' + pk)
    context = {
        'order_form':order_form,
        'address':address,
        'client':client,
        'order':order,
        'products':products,
    }
    return render(request, "backoffice/order-details.html", context)

@login_required(login_url="login")
def newOrderView(request):
    if request.method == 'POST':
        form = NewOrderForm(request.POST)
        if form.is_valid():
            new_order = form.save()
            products = request.POST.getlist('product')
            products_amount = request.POST.getlist('product_amount')
            # Cadastrar os produtos no product-list
            for i in range(len(products)):
                product = Product.objects.get(id = products[i])

backoffice/templates/backoffice/all-clients.html
{% extends "base/base.html" %}

{% load static %}

{% block title %} 
        <title>Store - Clientes</title>
{% endblock %}
 
{% block content %}
    <div class="container-fluid">
        <!-- Page Heading -->
        <h1 class="h3 mb-4 text-gray-800">Todos os Clientes</h1>
    </div>

    <div class="col-md-12">
        <div class="card card-body">
            <table class="table table-sm">
                <tr>
                    <th>Nome</th>
                    <th>Contato</th>
                    <th class="text-center">Opções</th>
                </tr>

                {% for client in clients %}
                    <tr>
                        <td><a href="{% url 'client-details' client.id %}">{{client.name}}</a></td>
                        <td><a target="_blank" href="https://api.whatsapp.com/send?phone=+55{{client.phone.number}}">{{client.phone.number}}</a></td>
                        <td class="d-flex justify-content-around">
                            <button class="btn btn-sm btn-primary">Editar</button>
                            <button class="btn btn-sm btn-danger" >Excluir</button>
                        </td>
                    </tr>
                {% endfor %}

        
            </table>
        </div>
    </div>
{% endblock %}

backoffice/templates/backoffice/all-orders.html
{% extends "base/base.html" %}

{% load static %}

{% block title %} 
        <title>Store - Pedidos</title>
{% endblock %}
 
{% block content %}
    <div class="container-fluid">
        <!-- Page Heading -->
        <h1 class="h3 mb-4 text-gray-800">Todos os Pedidos</h1>
    </div>

    <div class="col-md-12">
        <div class="card card-body">
            <table class="table table-sm">
                <tr>
                    <th>Código</th>
                    <th>Cliente</th>
                    <th>Data</th>
                    <th>Status</th>
                </tr>

                {% for order in orders %}
                    <tr>
                        <td><a href="{% url 'order-details' order.id %}">{{order.id}}</a></td>
                        <td>{{order.client}}</td>
                        <td>{{order.date}}</td>
                        <td>{{order.get_status_display}}</td>
                    </tr>
                {% endfor %}

        
            </table>
        </div>
    </div>
{% endblock %}

backoffice/templates/backoffice/all-spendings.html
{% extends "base/base.html" %}

{% load static %}

{% block title %} 
        <title>Store - Gastos</title>
{% endblock %}
 
{% block content %}
    <div class="container-fluid">
        <!-- Page Heading -->
        <h1 class="h3 mb-4 text-gray-800">Todos os Gastos</h1>
    </div>

    <div class="col-md-12">
        <div class="card card-body">
            <table class="table table-sm">
                <tr>
                    <th>Data</th>
                    <th>Tipo</th>
                    <th>Valor</th>
                </tr>

                {% for spending in spendings %}
                    <tr>
                        <td>{{spending.date}}</td>
                        <td>{{spending.get_tipo_display}}</td>
                        <td>{{spending.value}}</td>
                    </tr>
                {% endfor %}

        
            </table>
        </div>
    </div>
{% endblock %}

backoffice/templates/backoffice/new-client.html
{% extends "base/base.html" %}

{% load static %}

{% block title %} 
        <title>Store - Novo Cliente</title>
{% endblock %}
 
{% block content %}
    <div class="container-fluid">
        <!-- Page Heading -->
        <h1 class="h3 mb-4 text-gray-800">Inserir novo Cliente</h1>
    </div>
    <div class="row px-4">
        <div class="col-md-12">
            <div class="card card-body px-4">
                


                <form class="form-register" action="new-client" method="POST">
                    {% csrf_token %}
            
                    <p>Informação Pessoal</p>
                    
                    <label for="client_name" class="sr-only">Nome</label>
                    <input type="text" id="client_name" class="form-control my-2" placeholder="Nome do Cliente" name="name" required autofocus>

                    <label for="unique_identifier" class="sr-only">CPF</label>
                    <input type="text" id="unique_identifier" class="form-control my-2" placeholder="CPF do cliente" name="cpf" autofocus>

                    <p>Endereço</p>
                    
                    <div class="row">
                        <div class="col-sm-4 form-group">
                            <label for="id_number" class="sr-only">Numero:</label>
                            <input type="text" class="form-control" name="number" maxlength="15" placeholder="Número" required id="id_number">
                        </div>
                        <div class="col-sm-4 form-group">
                            <label for="id_street" class="sr-only">Rua:</label>
                            <input type="text" class="form-control" name="street" maxlength="254" placeholder="Rua" required id="id_street">
                        </div>
                        <div class="col-sm-4 form-group">
                            <label for="id_district" class="sr-only">Bairoo:</label>
                            <input type="text" class="form-control" name="district" maxlength="254" placeholder="Bairro" required id="id_district">
                        </div>
                    </div>
            
                    <div class="row">
                        
                        <div class="col-sm-4 form-group">
                            <label for="id_city" class="sr-only">Cidade:</label> 
                            <input type="text" class="form-control" name="city" maxlength="254" placeholder="Cidade" value="Rio Grande" required id="id_city">
                        </div>	
                        <div class="col-sm-4 form-group">
                            <label for="id_state" class="sr-only">Estado:</label>
                            <input type="text" class="form-control" name="state" maxlength="254" placeholder="Estado" value="Rio Grande do Sul" required id="id_state">
                        </div>	
                        <div class="col-sm-4 form-group">
                            <label for="id_postal_code" class="sr-only">CEP:</label>
                            <input type="text" class="form-control" name="postal_code" maxlength="31" placeholder="CEP" required id="id_postal_code">
                        </div>		
                    </div>

                    <div class="row">
                        <div class="col-sm-6 form-group">
                            <label for="id_latitude" class="sr-only">Latitude:</label> 
                            <input type="text" class="form-control" name="latitude" maxlength="31" placeholder="Latitude" required id="id_latitude">
                        </div>	
                        <div class="col-sm-6 form-group">
                            <label for="id_longitude" class="sr-only">Longitude:</label>
                            <input type="text" class="form-control" name="longitude" maxlength="31" placeholder="Longitude" required id="id_longitude">
                        </div>		
                    </div>

                    <label for="id_obs" class="sr-only">Informação Adicional</label>
                    <textarea class="form-control" name="address_description" rows="3" maxlength="254" placeholder="Informação Adicional" id="id_obs"></textarea>

                    <p class="pt-2">Contato</p>
                    <div>
                        <div id="phones" class="row">
                            <div class="col-sm-6 form-group">
                                <label for="client_phone" class="sr-only">Telefone/Celular</label>
                                <input type="text" id="client_phone" class="form-control my-2" placeholder="Telefone/Celular do Cliente" name="phone" required autofocus>
                            </div>
                            <div class="col-sm-6 form-group">
                                <label for="client_phone_obs" class="sr-only">CPF</label>
                                <input type="text" id="client_phone_obs" class="form-control my-2" placeholder="Fixo, Celular, Loja...?" value="Celular" name="phone_description" required autofocus>
                            </div>
                        </div>
                        <!--
                        <button type="button" id="add-phone" class="btn btn-warning">Adicionar Outro</button>
                        -->
                    </div>

                    <button class="btn btn-lg btn-primary btn-block mt-3" type="submit">Registrar</button>
                    
                </form>



            </div>
        </div>
    </div>

    <!-- Content Row -->
    <script src="{% static "vendor/jquery/jquery.min.js" %}"></script>
    <script>
        var index = 0;
        $(document.body).on('click', '.btn-remove-phone' ,function(){
            $(this).closest('.phone-input').remove();
        });
        
        
        $('#add-phone').on('click', function(){

            index += 1;
            
            $('#phones').append(
                '<div class="col-sm-6 form-group">'+
                    '<label for="client_phone" class="sr-only">Telefone/Celular</label>'+
                    '<input type="text" id="client_phone" class="form-control my-2" placeholder="Telefone/Celular do Cliente" name="phone['+index+']" required autofocus>'+
                '</div>'+
                '<div class="col-sm-6 form-group">'+
                        '<label for="client_phone_obs" class="sr-only">CPF</label>'+
                        '<input type="text" id="client_phone_obs" class="form-control my-2" placeholder="Fixo, Celular, Loja...?" value="Celular" name="phone_description['+index+']" required autofocus>'+
                '</div>'
            );
            
                
            
                
                
        });
    </script>

{% endblock %}

backoffice/templates/backoffice/order-details.html
{% extends "base/base.html" %}
{% load crispy_forms_tags %}

{% load static %}

{% block title %} 
        <title>Store - Detalhes do Pedido</title>
{% endblock %}
 
{% block content %}
    <div class="container-fluid">
        <!-- Page Heading -->
        <h1 class="h3 mb-4 text-gray-800">Pedido de {{client.name}}</h1>
    </div>
    
    <div class="row px-4">
        <div class="col-lg-6">
          <!-- Collapsable Card Example -->
            <div class="card shadow mb-4">
                <!-- Card Header - Accordion -->
                <a href="#address-information" class="d-block card-header py-3" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="address-information">
                    <h6 class="m-0 font-weight-bold text-primary">Informações do Pedido</h6>
                </a>
                <!-- Card Content - Collapse -->
                <div class="collapse show" id="address-information">
                    <div class="card-body">
                        <div class="list-group px-1 text-white">
                            <div class="list-group-item list-group-item-action flex-column align-items-start text-black my-2">
                                <p>Data do Pedido: {{order.date}}</p>
                                <p>Data Estimada para Entrega: {{order.delivery_estimate_date}}</p>
                                <p>Turno Estimado para Entrega: {{order.get_delivery_estimate_shift_display}}</p>
                                <p>Status: {{order.get_status_display}}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-6">
            <!-- Collapsable Card Example -->
            <div class="card shadow mb-4">
                <!-- Card Header - Accordion -->
                <a href="#personal-information" class="d-block card-header py-3" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="personal-information">
                    <h6 class="m-0 font-weight-bold text-primary">Produtos</h6>
                </a>
                <!-- Card Content - Collapse -->
                <div class="collapse show" id="personal-information">
                    <div class="card-body">
                        <div class="list-group-item list-group-item-action flex-column align-items-start my-2">
                            <table class="table table-sm">
                                <tr>
                                    <th>Nome</th>
                                    <th>Quantidade</th>
                                    <th>Valor</th>
                                </tr>
                
                                {% for product in products %}
                                    <tr>
                                        <td>{{product.product.title}}</td>
                                        <td>{{product.amount}}</td>
                                        <td>{{product.value}}</td>
                                    </tr>
                                {% endfor %}
                
                        
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <div class="col-lg-6">
            <!-- Collapsable Card Example -->
            <div class="card shadow mb-4">
                <!-- Card Header - Accordion -->
                <a href="#client_address_form" class="d-block card-header py-3" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="client_address_form">
                    <h6 class="m-0 font-weight-bold text-primary">Endereço do Cliente</h6>
                </a>
                <!-- Card Content - Collapse -->
                <div class="collapse show" id="client_address_form">
                    <div class="card-body">
                        <div class="flex-column align-items-start my-2">
                            <p>Número: {{address.number}}</p>
                            <p>Rua: {{address.street}}</p>
                            <p>Bairro: {{address.district}}</p>
                            <p>Estado: {{address.state}}</p>
                            <p>CEP: {{address.postal_code}}</p>
                            <p>Descrição: {{address.description}}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <div class="col-lg-6">
            <!-- Collapsable Card Example -->
            <div class="card shadow mb-4">
                <!-- Card Header - Accordion -->
                <a href="#client_form" class="d-block card-header py-3" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="client_form">
                    <h6 class="m-0 font-weight-bold text-primary">Atualizar Informações do Pedido</h6>
                </a>
                <!-- Card Content - Collapse -->
                <div class="collapse show" id="client_form">
                    <div class="card-body">
                        <div class="flex-column align-items-start my-2">
                            {{ order_form | crispy }}
                            <button class="btn btn-lg btn-primary btn-block mt-3" type="submit">Atualizar Pedido</button>
                        </div>
                        <form action="{% url 'order-delete' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" value="{{order.id}}" name="order">
                            <button class="btn btn-lg btn-danger btn-block mt-3" type="submit">Remover Pedido</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>


    </div>

    <!-- Content Row -->

{% endblock %}